#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(ROCK_HEART) \
    F(RIPTIDE) \
    F(ARC_FAULT) \
    F(GRASSPIERCER) \
    F(PSYCHE_LOCK) \
    F(POISONED_STARS) \
    F(MAGMATIC_RAGE) \
    F(SHALLOW_GRAVE) \
    F(WINDSTORM) \
    F(VINSECTICATION) \
    F(FUSSY_FUSS) \
    F(JINX) \
    F(CRASHING_FIST) \
    F(HYDRAULIC_PRESS) \
    F(ICE_RINK) \
    F(STORM_SACRIFICE) \
    F(MINERAGRAPHY) \
    F(SURFS_UP) \
    F(UNDERCURRENT) \
    F(THIRD_DEGREE) \
    F(INVERSION) \
    F(WING_SLICER) \
    F(GEMINIC_BLAST) \
    F(SHOWSTOPPER) \
    F(SINKHOLE) \
    F(SUNBLOOM) \
    F(AURA_FARMING) \
    F(WAKE_CRASH) \
    F(RAZZLE_DAZZLE) \
    F(STEELSURGE) \
    F(OVEREXPOSURE) \
    F(DRY_FULMINATION) \
    F(RESEARCH) \
    F(CHRYSALIS) \
    F(CASTING_CALL) \
    F(MOUNTING_PRESSURE) \
    F(JET_STREAM) \
    F(STUNT_DOUBLE) \
    F(CALAMITY_CLEAVE) \
    F(PSIDEKICK) \
    F(MOSH_PIT) \
    F(SYNCHRONIZED_SWIM) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
