#ifndef GUARD_CONSTANTS_TOURNEY_CONSTS_H
#define GUARD_CONSTANTS_TOURNEY_CONSTS_H

enum ParticipatingRegions{
    PART_REGION_NONE,
    PART_REGION_KANTO,
    PART_REGION_JOHTO,
    PART_REGION_HOENN,
    PART_REGION_SINNOH,
    PART_REGION_UNOVA,
    PART_REGION_KALOS,
    PART_REGION_ALOLA,
    PART_REGION_GALAR,
    PART_REGION_PALDEA,
    PART_REGIONS_COUNT,
};

#endif //GUARD_CONSTANTS_TOURNEY_CONSTS_H