Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed SOMEONE'S PC.\p"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.\p"
	.string "All items have been removed from your\n"
	.string "Pokémon.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accessed LANETTE's PC.$"
	.string "All items have been removed from\n"
	.string "your Pokémon."

gText_AccessedBillsPC::
	.string "Accessed BILL's PC.$"
