#ifndef GUARD_TOURNAMENT_OPPONENT_H
#define GUARD_TOURNAMENT_OPPONENT_H

#include "gba/types.h"

enum TournamentOpponentID
{
    T_OPPONENT_NONE,
    // Gen 1
    T_OPPONENT_BROCK,
    T_OPPONENT_MISTY,
    T_OPPONENT_LT_SURGE,
    T_OPPONENT_ERIKA,
    T_OPPONENT_SABRINA,
    T_OPPONENT_KOGA_AND_JANINE,
    T_OPPONENT_BLAINE,
    T_OPPONENT_GIOVANNI,
    // Gen 2
    T_OPPONENT_FALKNER,
    T_OPPONENT_BUGSY,
    T_OPPONENT_WHITNEY,
    T_OPPONENT_MORTY,
    T_OPPONENT_CHUCK,
    T_OPPONENT_JASMINE,
    T_OPPONENT_PRYCE,
    T_OPPONENT_CLAIR,
    // Gen 3
    T_OPPONENT_ROXANNE,
    T_OPPONENT_BRAWLY,
    T_OPPONENT_WATTSON,
    T_OPPONENT_FLANNERY,
    T_OPPONENT_NORMAN,
    T_OPPONENT_WINONA,
    T_OPPONENT_TATE_AND_LIZA,
    T_OPPONENT_JUAN,
    // Gen 4
    T_OPPONENT_ROARK,
    T_OPPONENT_GARDENIA,
    T_OPPONENT_MAYLENE,
    T_OPPONENT_CRASHER_WAKE,
    T_OPPONENT_FANTINA,
    T_OPPONENT_BYRON,
    T_OPPONENT_CANDICE,
    T_OPPONENT_VOLKNER,
    // Gen 5
    T_OPPONENT_LENORA,
    T_OPPONENT_BURGH,
    T_OPPONENT_ELESA,
    T_OPPONENT_CLAY,
    T_OPPONENT_SKYLA,
    T_OPPONENT_BRYCEN,
    T_OPPONENT_DRAYDEN,
    T_OPPONENT_CHEREN,
    T_OPPONENT_ROXIE,
    T_OPPONENT_MARLON,
    T_OPPONENT_COUNT,
};


struct TournamentOpponent
{
    const u8 *script;
    u16 graphicsId;
};

extern const struct TournamentOpponent gTournamentOpponents[T_OPPONENT_COUNT];

#endif // GUARD_TOURNAMENT_OPPONENT_H
